### ISSUE TITLE
You can actually use `using x for y`

### ISSUE THREAD

**Issue by chriseth** [figs999/Ethereum#2]
https://github.com/figs999/Ethereum/blob/c4ba7967ad0c3c0a80f4062d03f42ca8986caea6/VirtualStruct.sol#L26

- internal library functions do not use delegatecall and if the type is a value type, it does not even use memory.

**Comment by figs999** [comment]
Huh... That's odd, I definitely saw the behavior of it using delegatecall when I was debugging in remix.

Would that behavior require the optimizer?

I'll check it again.

**Comment by figs999** [comment]
Yep, it was the optimizer being turned off :)

**Comment by figs999** [comment]
Just committed an update which changes it back to a library.

@chriseth Any idea why the library call version of the read function would cost 9 gas more than the old version? It's an odd amount considering that it's 5 calls into the library... 1 function cost 1 more and the rest cost 2? I'm probably going to do a deeper dive into the opcodes around that method at some point, considering the optimizer actually got the built-in struct read even lower.

**Comment by chriseth** [comment]
Great! The additional costs might come from some "Swapity swap" :)
