### ISSUE TITLE
EXP 100**0

### ISSUE THREAD

**Issue by withzombies** [figs999/Ethereum#3]
https://github.com/figs999/Ethereum/blob/c4ba7967ad0c3c0a80f4062d03f42ca8986caea6/Solc.aComedyInOneAct#L121-L123

Hey, I've noticed the 100**0 thing as well. Do you know what solidity code (and compiler) creates it?

**Comment by figs999** [comment]
Yeah, it's part of a generic routine for getting the bitmask for composing structs into a storage bucket.

Specifically, it is the pattern: 0100^n, where n is the byte index of the struct property in question. 

It just does this regardless of if the property is in fact at index 0.
